import { useMemo } from "react";
import { MemberLayout } from "@/components/member/MemberLayout";
import { useAuth } from "@/contexts/AuthContext";
import { useAccounts, useTrades } from "@/hooks/use-member-data";
import { calculateAnalytics } from "@shared/member";

export default function AnalyticsPage() {
  const { profile } = useAuth(); const { data: accounts = [] } = useAccounts(profile?.id); const primary = accounts.find((account) => account.is_primary) || accounts[0]; const { data: trades = [] } = useTrades(profile?.id, primary?.id); const summary = useMemo(() => calculateAnalytics(trades), [trades]);
  const symbols = useMemo(() => Object.entries(trades.reduce<Record<string, { pnl: number; count: number }>>((map, trade) => { const item = map[trade.symbol] || { pnl: 0, count: 0 }; item.pnl += Number(trade.net_pnl); item.count++; map[trade.symbol] = item; return map; }, {})).sort((a,b) => b[1].pnl-a[1].pnl), [trades]);
  const emotions = useMemo(() => Object.entries(trades.reduce<Record<string, { pnl: number; count: number }>>((map, trade) => { const item = map[trade.emotion] || { pnl: 0, count: 0 }; item.pnl += Number(trade.net_pnl); item.count++; map[trade.emotion] = item; return map; }, {})).sort((a,b) => b[1].pnl-a[1].pnl), [trades]);
  return <MemberLayout><p className="text-[10px] uppercase tracking-[0.2em] text-white/35">Performance</p><h1 className="mt-3 font-sans text-3xl font-semibold normal-case tracking-[-0.04em]">Analytics</h1><p className="mt-2 text-sm text-white/38">Patterns from {primary?.name || "your selected account"}.</p><div className="mt-10 grid grid-cols-2 gap-6 lg:grid-cols-4"><Stat label="Trades" value={String(trades.length)} /><Stat label="Win rate" value={`${summary.winRate.toFixed(1)}%`} /><Stat label="Profit factor" value={summary.profitFactor === null ? "∞" : summary.profitFactor.toFixed(2)} /><Stat label="Plan adherence" value={`${summary.planAdherence.toFixed(0)}%`} /></div><div className="mt-12 grid gap-12 lg:grid-cols-2"><Breakdown title="By symbol" rows={symbols} currency={primary?.currency} /><Breakdown title="By emotion" rows={emotions} currency={primary?.currency} /></div></MemberLayout>;
}
function Stat({ label, value }: { label: string; value: string }) { return <div className="border-t border-white/10 pt-4"><p className="text-[9px] uppercase tracking-wider text-white/30">{label}</p><p className="mt-3 font-display text-2xl font-semibold">{value}</p></div>; }
function Breakdown({ title, rows, currency }: { title: string; rows: Array<[string,{pnl:number;count:number}]>; currency?: string }) { return <section><h2 className="font-sans text-base font-semibold normal-case tracking-normal">{title}</h2><div className="mt-5 divide-y divide-white/[0.07]">{rows.map(([name,item]) => <div key={name} className="flex justify-between py-4 text-sm"><span className="capitalize text-white/55">{name} <small className="ml-2 text-white/25">{item.count}</small></span><span className={item.pnl >= 0 ? "text-white" : "text-white/40"}>{currency} {item.pnl.toFixed(2)}</span></div>)}{rows.length === 0 && <p className="py-8 text-sm text-white/30">No trade data yet.</p>}</div></section>; }
