import { useMemo, useState } from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { MemberLayout } from "@/components/member/MemberLayout";
import { useAuth } from "@/contexts/AuthContext";
import { useAccounts, useTrades } from "@/hooks/use-member-data";

export default function CalendarPage() {
  const { profile } = useAuth(); const { data: accounts = [] } = useAccounts(profile?.id); const primary = accounts.find((account) => account.is_primary) || accounts[0]; const { data: trades = [] } = useTrades(profile?.id, primary?.id); const [month, setMonth] = useState(() => new Date());
  const year = month.getFullYear(), index = month.getMonth(), firstOffset = (new Date(year, index, 1).getDay() + 6) % 7, days = new Date(year, index + 1, 0).getDate();
  const totals = useMemo(() => trades.reduce<Record<number,number>>((map, trade) => { const date = new Date(trade.closed_at); if (date.getFullYear() === year && date.getMonth() === index) map[date.getDate()] = (map[date.getDate()] || 0) + Number(trade.net_pnl); return map; }, {}), [trades, year, index]);
  const monthTotal = Object.values(totals).reduce((sum,value) => sum+value,0);
  return <MemberLayout><div className="flex items-end justify-between"><div><p className="text-[10px] uppercase tracking-[0.2em] text-white/35">Daily results</p><h1 className="mt-3 font-sans text-3xl font-semibold normal-case tracking-[-0.04em]">P&amp;L calendar</h1><p className="mt-2 text-sm text-white/38">{primary ? `${primary.name} · ${primary.currency} ${monthTotal.toFixed(2)}` : "Create a trading account to begin."}</p></div><div className="flex items-center gap-2"><button aria-label="Previous month" onClick={() => setMonth(new Date(year,index-1,1))} className="grid size-9 place-items-center border border-white/10"><ChevronLeft className="size-4" /></button><span className="w-28 text-center text-xs">{month.toLocaleDateString("en-ZA", {month:"long",year:"numeric"})}</span><button aria-label="Next month" onClick={() => setMonth(new Date(year,index+1,1))} className="grid size-9 place-items-center border border-white/10"><ChevronRight className="size-4" /></button></div></div><div className="mt-10 grid grid-cols-7 gap-px bg-white/[0.08] border border-white/[0.08]">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map((day) => <div key={day} className="bg-black p-3 text-[9px] uppercase tracking-wider text-white/25">{day}</div>)}{Array.from({length:firstOffset}).map((_,i) => <div key={`x${i}`} className="min-h-24 bg-black" />)}{Array.from({length:days},(_,i)=>i+1).map((day) => <div key={day} className={`min-h-24 bg-black p-3 ${totals[day] ? "bg-white/[0.025]" : ""}`}><p className="text-xs text-white/35">{day}</p>{totals[day] != null && <p className={`mt-5 font-mono text-xs ${totals[day] >= 0 ? "text-white" : "text-white/35"}`}>{totals[day] >= 0 ? "+" : ""}{totals[day].toFixed(2)}</p>}</div>)}</div></MemberLayout>;
}
